version: '3.4'
 
services:

  candles:
    image: kebacode/candlescontroller:v2
    build:
      context: .
      dockerfile: Candles/Dockerfile
    ports:
      - 44307:80 # HOST:CONTAINER 
    environment:
      MAXVALUESSERVICE_PORT: 80
      MAXVALUESSERVICE_ADDRESS: maxvaluecontroller
    depends_on:
      - maxvaluecontroller
    networks:
    - asd
  maxvaluecontroller:
    image: kebacode/maxvaluecontroller:v2
    build:
      context: .
      dockerfile: MaxValueController/Dockerfile
    ports:
      - 44359:80 # HOST:CONTAINER
    networks:
    - asd
networks:
  asd:
    driver: bridge