version: '3.4'

services:
  maxvaluecontroller:
    image: ${DOCKER_REGISTRY-}maxvaluecontroller
    restart: always
    build:
      context: .
      dockerfile: MaxValueController/Dockerfile

  candles:
    image: ${DOCKER_REGISTRY-}candles
    restart: always
    build:
      context: .
      dockerfile: Candles/Dockerfile
    environment:
      MAXVALUESSERVICE_PORT: 44358
    depends_on:
      - maxvaluecontroller