apiVersion: v1
kind: Service
metadata:
  name: candles-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-candles-app
  ports:
  - port: 80
    nodePort: 32444
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: max-value-svc
spec:
  selector:
    app: kube-maxvalues-app
  ports:
  - port: 80
    targetPort: http
